name: rgc_test_apk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  objectbox: ^2.5.0
  objectbox_flutter_libs: ^2.5.0
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  objectbox_generator: ^2.5.1

flutter:
  uses-material-design: true

  fonts:
      - family: PlusJakartaSans
        fonts:
          - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
            weight: 500
